### PR TITLE
so.devops.

### PR DESCRIPTION
**Pull request by rickscherer**
this is how you put the dev into ops.

### CODE REVIEW

**Comment by jonasrosland** [comment]
Look at #15

**Comment by rickscherer** [comment]
#15 is weak.

**Comment by jonasrosland** [comment]
LGTM

**Comment by rickscherer** [comment]
hell yeah it does.

**Comment by timeisanillusion** [comment]
I think #15 is excellent!

**Comment by rickscherer** [comment]
b2b8f8441aa4811dcac169a9a5daba7e618b089a3271e525711cc4bcf95d891e

**Pull request merged**
